version: "3.8"

services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWOR: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./.docker/mysql_data:/var/lib/mysql
    networks:
      - sevenz_health

  api:
    container_name: api
    build: 
      context: ./.docker
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - sevenz_health
  
  web:
    container_name: web
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - .docker/nginx_local_template.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3050:80"
    depends_on:
      - api
    networks:
      - sevenz_health

volumes:
  mysql_data:
networks:
  sevenz_health:
    driver: bridge